config/routes.rb
Rails.application.routes.draw do
  resources :addresses

end

app/models/address.rb
class Address < ActiveRecord::Base
end

app/controllers/addresses_controller.rb
class AddressesController < ApplicationController
	def index
	end
	 
	def new
	  @address = Address.new
	end
	 
	def create
	  @address = current_user.addresses.create(address_params)
	  if @address.save
	    redirect_to addresses_path
	  else
	    render action: 'new'
	  end
	end

	private 
	  def address_params
	    params[:address].permit(:address, :description, :user_id)
	  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/helpers/addresses_helper.rb
module AddressesHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/addresses/index.html.erb
<%= link_to 'New Note', new_note_path %> 
<%= link_to 'Addresses', addresses_path %>
<%= link_to ' | Logout', logout_path if logged_in? %>

<div id="map_canvas"></div>

app/views/addresses/new.html.erb
Add a new Marker!
 
<%= form_for @address do |f| %>
  <%= f.text_field :address, :placeholder => "Address" %>
  <%= f.text_field :description, :placeholder => "Description"%><br>
  <%= f.submit "Add" %>
<% end %> 

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>BasketballMap</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

<script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyC7B_uc7RTcpTTrfqpqHu0XJu3z6o3K8wU&sensor=false"> </script>

<script type="text/javascript">
function initialize(latitude, longitude) {
  var mapOptions = {
      center: new google.maps.LatLng(latitude, longitude),
      zoom: 15,
      mapTypeId: google.maps.MapTypeId.ROADMAP
  };
  var map = new google.maps.Map(document.getElementById("map_canvas"),
      mapOptions);
}
 
$(function() {
  initialize(latitude, longitude);
});
 
var latitude  = 40.726477<%#= @latit %>;
var longitude = -73.981534<%#= @longt %>;
 
</script>

<%= link_to "New Marker", new_address_path %>
<%= link_to "| Back to Notes", notes_path %>

</body>
</html>